#!/bin/bash

git push --delete origin create-PR
git checkout -b create-PR

VERSION=$(cat package.json | grep -o '\"version\": \"[^\"]*' | grep -o '[^\"]*$')

echo ====================================
echo See: https://github.com/tyankatsu0105/sandbox-actions/pulls\?utf8=%E2%9C%93\&q=head\:release\/$VERSION
echo ====================================

git branch -D create-PR