name: Access Repository

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'gridsome/eslint-plugin-gridsome'
          ref: 'master'

      - name: ls
        shell: bash
        run: |
          ls -a